---
title: "150_V2_Output summary"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(kableExtra)

complete <- read.delim("~/Github/MVP-NonClinalAF/sim_output_summary/completedSamplesList.txt",header=F)
colnames(complete) <- "complete"
complete$isComplete <- TRUE
started <- read.delim("~/Github/MVP-NonClinalAF/sim_output_summary/startedSamplesList.txt",header = F)
colnames(started) <- "start"
started$isStarted <- TRUE
paramList <- read.delim("~/Github/MVP-NonClinalAF/sim_output_summary/parameterslist_150_V2.txt",sep = " ")
```

```{r}
paramList <- left_join(paramList,started,by=c("seed"="start"))
paramList$isStarted[!paramList$isStarted] <- FALSE
paramList <- left_join(paramList,complete,by=c("seed"="complete"))
paramList$isComplete[is.na(paramList$isComplete)] <- FALSE

paramListIncomplete <- paramList[paramList$isComplete == F,]
```

**Samples that failed to complete due to time**

```{r}
kable(paramListIncomplete,format = "html",) %>%
  kable_styling(full_width = F)
```
